services:

  laravel-php8:
    image: php8
    container_name: laravel-php8
    build: .
    volumes:
      - ./start-laravel:/var/www/html
    ports:
      - 80:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_php8
    ports:
    - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1

